<?php
namespace App\Models;

/**
 * Prodotti
 * 
 * @package App\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2026-08-10, 17:16:42
 */
class Prodotto extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $reparto_id;

    /**
     *
     * @var string
     */
    protected $sku;

    /**
     *
     * @var string
     */
    protected $nome;

    /**
     *
     * @var string
     */
    protected $descrizione;

    /**
     *
     * @var double
     */
    protected $prezzo_listino;

    /**
     *
     * @var double
     */
    protected $aliquota_iva;

    /**
     *
     * @var string
     */
    protected $unita_misura;

    /**
     *
     * @var integer
     */
    protected $biologico;

    /**
     *
     * @var integer
     */
    protected $attivo;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field reparto_id
     *
     * @param integer $reparto_id
     * @return $this
     */
    public function setRepartoId($reparto_id)
    {
        $this->reparto_id = $reparto_id;

        return $this;
    }

    /**
     * Method to set the value of field sku
     *
     * @param string $sku
     * @return $this
     */
    public function setSku($sku)
    {
        $this->sku = $sku;

        return $this;
    }

    /**
     * Method to set the value of field nome
     *
     * @param string $nome
     * @return $this
     */
    public function setNome($nome)
    {
        $this->nome = $nome;

        return $this;
    }

    /**
     * Method to set the value of field descrizione
     *
     * @param string $descrizione
     * @return $this
     */
    public function setDescrizione($descrizione)
    {
        $this->descrizione = $descrizione;

        return $this;
    }

    /**
     * Method to set the value of field prezzo_listino
     *
     * @param double $prezzo_listino
     * @return $this
     */
    public function setPrezzoListino($prezzo_listino)
    {
        $this->prezzo_listino = $prezzo_listino;

        return $this;
    }

    /**
     * Method to set the value of field aliquota_iva
     *
     * @param double $aliquota_iva
     * @return $this
     */
    public function setAliquotaIva($aliquota_iva)
    {
        $this->aliquota_iva = $aliquota_iva;

        return $this;
    }

    /**
     * Method to set the value of field unita_misura
     *
     * @param string $unita_misura
     * @return $this
     */
    public function setUnitaMisura($unita_misura)
    {
        $this->unita_misura = $unita_misura;

        return $this;
    }

    /**
     * Method to set the value of field biologico
     *
     * @param integer $biologico
     * @return $this
     */
    public function setBiologico($biologico)
    {
        $this->biologico = $biologico;

        return $this;
    }

    /**
     * Method to set the value of field attivo
     *
     * @param integer $attivo
     * @return $this
     */
    public function setAttivo($attivo)
    {
        $this->attivo = $attivo;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field reparto_id
     *
     * @return integer
     */
    public function getRepartoId()
    {
        return $this->reparto_id;
    }

    /**
     * Returns the value of field sku
     *
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Returns the value of field nome
     *
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * Returns the value of field descrizione
     *
     * @return string
     */
    public function getDescrizione()
    {
        return $this->descrizione;
    }

    /**
     * Returns the value of field prezzo_listino
     *
     * @return double
     */
    public function getPrezzoListino()
    {
        return $this->prezzo_listino;
    }

    /**
     * Returns the value of field aliquota_iva
     *
     * @return double
     */
    public function getAliquotaIva()
    {
        return $this->aliquota_iva;
    }

    /**
     * Returns the value of field unita_misura
     *
     * @return string
     */
    public function getUnitaMisura()
    {
        return $this->unita_misura;
    }

    /**
     * Returns the value of field biologico
     *
     * @return integer
     */
    public function getBiologico()
    {
        return $this->biologico;
    }

    /**
     * Returns the value of field attivo
     *
     * @return integer
     */
    public function getAttivo()
    {
        return $this->attivo;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("supermercato_demo");
        $this->setSource("prodotti");
        $this->hasMany('id', 'App\Models\OrdiniProdotti', 'prodotto_id', ['alias' => 'OrdiniProdotti']);
        $this->hasMany('id', 'App\Models\ProdottiFornitori', 'prodotto_id', ['alias' => 'ProdottiFornitori']);
        $this->hasMany('id', 'App\Models\PromozioniProdotti', 'prodotto_id', ['alias' => 'PromozioniProdotti']);
        $this->hasMany('id', 'App\Models\SupermercatiProdotti', 'prodotto_id', ['alias' => 'SupermercatiProdotti']);
        $this->belongsTo('reparto_id', 'App\Models\Reparti', 'id', ['alias' => 'Reparti']);
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Prodotti[]|Prodotti|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null): \Phalcon\Mvc\Model\ResultsetInterface
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Prodotti|\Phalcon\Mvc\Model\ResultInterface|\Phalcon\Mvc\ModelInterface|null
     */
    public static function findFirst($parameters = null): ?\Phalcon\Mvc\ModelInterface
    {
        return parent::findFirst($parameters);
    }

}
